# Generated by Django 5.2 on 2025-08-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('image_main', models.ImageField(upload_to='products/')),
                ('image_thumb1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_thumb2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_thumb3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sizes', models.ManyToManyField(blank=True, to='myApp.size')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
