# Generated by Django 5.2 on 2025-08-09 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_order_remove_booking_user_delete_guide_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
