# Generated by Django 5.2 on 2025-08-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_remove_orderitem_product_orderitem_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.URLField(default='Unknown Product', max_length=500),
            preserve_default=False,
        ),
    ]
