# Generated by Django 5.2 on 2025-08-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_remove_orderitem_image_url_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
