# Generated by Django 5.2 on 2025-08-10 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_remove_order_address_remove_order_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
