# Generated by Django 5.2 on 2025-08-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
